## RAG Assignment: Baseline vs. Re-Ranking

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0" 

import re, time, json, collections
import numpy as np
import fitz # PyMuPDF
import faiss
import torch
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

/home/priyanka/miniconda3/envs/myenv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
EMB_MODEL     = "BAAI/bge-m3"
LLM_NAME      = "Qwen/Qwen3-8B"
CHUNK_SIZE    = 1000  # characters (~250 tokens)
CHUNK_OVERLAP = 150
TOP_K         = 10 # retrieved candidates
TOP_N         = 3 # chunks given to the LLM
MAX_NEW_TOK   = 300
DEVICE        = "cuda"

### 1. Dataset

In [3]:
# Appel's annual report

PDF_PATH = "data/report.pdf"

In [4]:
# extract text page by page
doc = fitz.open(PDF_PATH)
pages = []
for i, page in enumerate(doc):
    # sort=True gives a more natural reading order for multi-column layouts
    pages.append({"page": i + 1, "text": page.get_text("text", sort=True)})
print("pages:", len(pages))

pages: 80

In [5]:
def find_boilerplate(pages, min_frac=0.3):
    """Lines that appear on >= min_frac of pages are treated as headers/footers."""
    counter = collections.Counter()
    for p in pages:
        # digits -> "#" so page-numbered footers ("... | 10-K | 35") match across pages
        counter.update({re.sub(r"\d+", "#", ln.strip()) for ln in p["text"].splitlines() if ln.strip()})
    thresh = max(3, int(len(pages) * min_frac))
    return {ln for ln, c in counter.items() if c >= thresh and len(ln) < 120}
 
boiler = find_boilerplate(pages)
print("boilerplate lines removed:", list(boiler))

boilerplate lines removed: ['Apple Inc. | # Form #-K | #']

In [6]:
def clean(text):
    lines = [ln for ln in text.splitlines() if re.sub(r"\d+", "#", ln.strip()) not in boiler]
    text = "\n".join(lines)
    text = re.sub(r"-\n(\w)", r"\1", text)      # join hyphenated line breaks
    text = re.sub(r"\n{2,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"(?<!\n)\n(?!\n)", " ", text)  # single newlines -> space
    return text.strip()

In [7]:
for p in pages:
    p["text"] = clean(p["text"])

### 2. Two-Stage Retrieval

#### A. Baseline Retrieval - Pipeline 1

In [8]:
# chunking (within each page, so page metadata stays exact)
def chunk_text(text, size=CHUNK_SIZE, overlap=CHUNK_OVERLAP):
    chunks, start, n = [], 0, len(text)
    while start < n:
        end = min(start + size, n)
        if end < n:                                   # snap to a sentence / space boundary
            cut = text.rfind(". ", start, end)
            if cut > start + size * 0.6:
                end = cut + 1
            else:
                sp = text.rfind(" ", start, end)
                if sp > start + size * 0.6:
                    end = sp
        piece = text[start:end].strip()
        if len(piece) > 50:
            chunks.append(piece)
        if end >= n:
            break
        start = max(end - overlap, start + 1)
        sp = text.find(" ", start, end)              # don't start mid-word
        if sp != -1:
            start = sp + 1
    return chunks

In [9]:
chunks = []   # list of dicts: chunk_id, page, text
for p in pages:
    for t in chunk_text(p["text"]):
        chunks.append({"chunk_id": len(chunks), "page": p["page"], "text": t})
print("total chunks:", len(chunks))
 
import random
for c in random.sample(chunks, 5):
    print(f"--- chunk {c['chunk_id']} (page {c['page']}) ---\n{c['text']}\n")
 
# helpers for finding gold chunks when you write failure queries later
def show_chunk(i):
    c = chunks[i]
    print(f"[chunk {c['chunk_id']} | page {c['page']}]\n{c['text']}")
 
def find_chunks(keyword, limit=20):
    kw = keyword.lower()
    hits = [c["chunk_id"] for c in chunks if kw in c["text"].lower()]
    print(f"'{keyword}' appears in {len(hits)} chunks:", hits[:limit])
    return hits

total chunks: 376
--- chunk 144 (page 24) ---
Item 7. Management’s Discussion and Analysis of Financial Condition and Results of Operations

The following discussion should be read in conjunction with the consolidated financial statements and accompanying notes included in Part II, Item 8 of this Form 10-K. This Item generally discusses 2025 and 2024 items and year-to-year comparisons between 2025 and 2024. Discussions of 2023 items and year-to-year comparisons between 2024 and 2023 are not included, and can be found in “Management’s Discussion and Analysis of Financial Condition and Results of Operations” in Part II, Item 7 of the Company’s Annual Report on Form 10-K for the fiscal year ended September 28, 2024.

Product, Service and Software Announcements

The Company announces new product, service and software offerings at various times during the year.

--- chunk 7 (page 3) ---
Apple Inc.

 Form 10-K

 For the Fiscal Year Ended September 27, 2025

 TABLE OF CONTENTS

 Page

 Part I

Item 1. Business 1

Item 1A. Risk Factors 5

Item 1B. Unresolved Staff Comments 17

Item 1C. Cybersecurity 17

Item 2. Properties 17

Item 3. Legal Proceedings 18

Item 4. Mine Safety Disclosures 18

 Part II

Item 5. Market for Registrant’s Common Equity, Related Stockholder Matters and Issuer Purchases of Equity 19  Securities

Item 6. [Reserved] 20

Item 7. Management’s Discussion and Analysis of Financial Condition and Results of Operations 21

Item 7A. Quantitative and Qualitative Disclosures About Market Risk 27

Item 8. Financial Statements and Supplementary Data 28

Item 9. Changes in and Disagreements with Accountants on Accounting and Financial Disclosure 52

Item 9A. Controls and Procedures 52

Item 9B. Other Information 53

Item 9C. Disclosure Regarding Foreign Jurisdictions that Prevent Inspections 53

 Part III

Item 10.

--- chunk 223 (page 45) ---
$ 1,579 $ 1,488

 Other non-current liabilities 10,911 10,046

 Finance leases Other current liabilities 538 144

 Other non-current liabilities 692 752

 Total lease liabilities $ 13,720 $ 12,430

--- chunk 67 (page 12) ---
terms, or at all.

The Company’s products and services include technology or intellectual property that must be licensed from third parties. In addition, because of technological changes in the industries in which the Company currently competes or in the future may compete, current extensive intellectual property coverage and the rapid rate of new intellectual property rights generation, the Company’s products and services may be alleged to infringe existing intellectual property rights of others. This risk may be exacerbated by the use of new and emerging technologies, including machine learning and artificial intelligence, which can involve, among other things, the acquisition and use of copyrighted materials for training as well as the potential reproduction of copyrighted materials in their outputs. From time to time, the Company has been notified that it may be infringing certain intellectual property rights of third parties.

--- chunk 2 (page 2) ---
Indicate by check mark whether the Registrant (1) has filed all reports required to be filed by Section 13 or 15(d) of the Securities Exchange Act of 1934 during the preceding 12 months (or for such shorter period that the Registrant was required to file such reports), and (2) has been subject to such filing requirements for the past 90 days.  Yes ☒ No ☐

Indicate by check mark whether the Registrant has submitted electronically every Interactive Data File required to be submitted pursuant to Rule 405 of Regulation S-T (§232.405 of this chapter) during the preceding 12 months (or for such shorter period that the Registrant was required to submit such files).  Yes ☒ No ☐

Indicate by check mark whether the Registrant is a large accelerated filer, an accelerated filer, a non-accelerated filer, a smaller reporting company, or an emerging growth company.

In [10]:
# embed chunks with the bi-encoder and build the FAISS index
embedder = SentenceTransformer(EMB_MODEL, device=DEVICE)
embedder.half()
embedder.max_seq_length = 512
 
texts = [c["text"] for c in chunks]
emb_path = "chunk_embeddings.npy"
if os.path.exists(emb_path):
    chunk_emb = np.load(emb_path)
else:
    chunk_emb = embedder.encode(texts, batch_size=64, normalize_embeddings=True,
                                convert_to_numpy=True, show_progress_bar=True)
    np.save(emb_path, chunk_emb)
chunk_emb = np.ascontiguousarray(chunk_emb.astype("float32"))
print("embeddings:", chunk_emb.shape)
 
# normalized vectors => inner product == cosine similarity
index = faiss.IndexFlatIP(chunk_emb.shape[1])
index.add(chunk_emb)
print("vectors in index:", index.ntotal)

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 34200.30it/s]
Batches: 100%|██████████| 6/6 [00:00<00:00,  7.26it/s]

embeddings: (376, 1024)
vectors in index: 376

In [11]:
# retrieval function (top 10) + NumPy cross-check
def embed_query(q):
    return embedder.encode([q], normalize_embeddings=True, convert_to_numpy=True).astype("float32")
 
def retrieve_topk(query, k=TOP_K):
    qv = embed_query(query)
    scores, ids = index.search(qv, k)
    return [(int(i), float(s)) for i, s in zip(ids[0], scores[0])]

In [12]:
# verify FAISS against a plain NumPy dot product (should give the same ranking)
q = "test query"
qv = embed_query(q)
np_top = np.argsort(-(chunk_emb @ qv[0]))[:TOP_K].tolist()
assert np_top == [i for i, _ in retrieve_topk(q)], "FAISS and NumPy rankings differ!"
print("FAISS == NumPy check passed")

FAISS == NumPy check passed

In [13]:
# load Qwen3-8B
tok = AutoTokenizer.from_pretrained(LLM_NAME)
llm = AutoModelForCausalLM.from_pretrained(LLM_NAME, torch_dtype=torch.bfloat16, device_map=DEVICE)
llm.eval()

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 399/399 [00:04<00:00, 85.37it/s]

Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 4096)
    (layers): ModuleList(
      (0-35): 36 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=4096, out_features=12288, bias=False)
          (up_proj): Linear(in_features=4096, out_features=12288, bias=False)
          (down_proj): Linear(in_features=12288, out_features=4096, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((4096,), eps=1e-06)
    (rotary_emb): Qwen3RotaryEmbedding()
  )
  (lm_head): Linear(in_features=4096, out_features=151936, bias=False)
)

In [14]:
# %% Cell 8: ONE prompt builder + ONE generate function, reused by BOTH pipelines
SYSTEM_PROMPT = (
    "You are a careful assistant answering questions about a document. "
    "Use ONLY the provided context. If the context does not contain the answer, "
    "say 'The context does not contain this information.' Be concise and precise, "
    "and mention any conditions, exceptions or restrictions stated in the context."
)
 
def build_prompt(query, chunk_ids):
    ctx = "\n\n".join(
        f"[Chunk {i} | page {chunks[i]['page']}]\n{chunks[i]['text']}" for i in chunk_ids
    )
    user = f"Context:\n{ctx}\n\nQuestion: {query}\n\nAnswer:"
    return [{"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user}]
 
@torch.no_grad()
def generate(messages, max_new_tokens=MAX_NEW_TOK):
    # enable_thinking=False turns off Qwen3's <think> mode so answers are short and comparable
    text = tok.apply_chat_template(messages, tokenize=False,
                                   add_generation_prompt=True, enable_thinking=False)
    inputs = tok(text, return_tensors="pt").to(llm.device)
    out = llm.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False,
                       temperature=None, top_p=None, top_k=None)   # greedy: deterministic
    return tok.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True).strip()

In [15]:
# Pipeline 1 end to end
def sync():
    if torch.cuda.is_available():
        torch.cuda.synchronize()
 
def baseline(query):
    t0 = time.perf_counter()
    top10 = retrieve_topk(query, TOP_K)          # [(chunk_id, cosine), ...] sorted desc
    sync(); t_retr = time.perf_counter() - t0
 
    top3_ids = [i for i, _ in top10[:TOP_N]]     # take the top 3 directly
    t1 = time.perf_counter()
    answer = generate(build_prompt(query, top3_ids))
    sync(); t_llm = time.perf_counter() - t1
 
    return {"query": query, "top10": top10, "top3_ids": top3_ids, "answer1": answer,
            "retrieval_ms": t_retr * 1000, "llm_s": t_llm}

In [16]:
def print_result(r):
    print("QUERY:", r["query"])
    print("Top-10 (rank, chunk_id, page, cosine):")
    for rank, (i, s) in enumerate(r["top10"], 1):
        mark = " <- sent to LLM" if rank <= TOP_N else ""
        print(f"  #{rank:<2} chunk {i:<5} p.{chunks[i]['page']:<4} {s:.4f}{mark}")
    print("ANSWER 1:", r["answer1"])
    print(f"retrieval {r['retrieval_ms']:.1f} ms | LLM {r['llm_s']:.1f} s\n")
 
# %% Cell 10: smoke test (replace with a real question about YOUR document)
res = baseline("what is the report about?")
print_result(res)

QUERY: what is the report about?
Top-10 (rank, chunk_id, page, cosine):
  #1  chunk 263   p.55   0.5195 <- sent to LLM
  #2  chunk 254   p.54   0.5189 <- sent to LLM
  #3  chunk 9     p.4    0.5170 <- sent to LLM
  #4  chunk 372   p.79   0.4996
  #5  chunk 367   p.78   0.4978
  #6  chunk 267   p.57   0.4962
  #7  chunk 253   p.54   0.4952
  #8  chunk 32    p.7    0.4915
  #9  chunk 246   p.52   0.4910
  #10 chunk 371   p.79   0.4855
ANSWER 1: The report is about the Company's internal control over financial reporting, including the audit opinion provided by Ernst & Young LLP, the absence of changes in internal control during the fourth quarter of 2025, and the basis for the audit opinion. It also mentions that the report contains forward-looking statements regarding the Company's business and results of operations.
retrieval 15.7 ms | LLM 1.6 s

#### B. Re-Ranking - Pipeline 2

In [17]:
from sentence_transformers import CrossEncoder

CE_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

# the cross-encoder reads (query, chunk) as ONE sequence -> joint attention over both
reranker = CrossEncoder(CE_MODEL, device=DEVICE, max_length=512)

# warm-up so the first timed query doesn't include CUDA / kernel start-up
reranker.predict([("warm up", chunks[0]["text"])])
embed_query("warm up")

Loading weights: 100%|██████████| 105/105 [00:00<00:00, 8514.95it/s]

array([[ 0.02116394,  0.02047729, -0.04849243, ..., -0.00387192,
        -0.01230621,  0.03897095]], shape=(1, 1024), dtype=float32)

In [18]:
def rerank(query, top10):
    """Score all 10 (query, chunk) pairs with the cross-encoder, sort descending.
    Returns [(chunk_id, ce_score, bi_rank), ...] where bi_rank is the original rank (1-10)."""
    pairs = [(query, chunks[i]["text"]) for i, _ in top10]
    ce_scores = reranker.predict(pairs, batch_size=len(pairs), convert_to_numpy=True)
    ranked = [(i, float(s), r) for r, ((i, _), s) in enumerate(zip(top10, ce_scores), 1)]
    return sorted(ranked, key=lambda x: x[1], reverse=True)

def reranked_pipeline(query):
    t0 = time.perf_counter()
    top10 = retrieve_topk(query, TOP_K)          # same top-10 candidates as Pipeline 1
    sync(); t_retr = time.perf_counter() - t0

    t1 = time.perf_counter()
    ranked = rerank(query, top10)
    sync(); t_rr = time.perf_counter() - t1

    top3_ids = [i for i, _, _ in ranked[:TOP_N]] # top 3 after re-ranking
    t2 = time.perf_counter()
    answer = generate(build_prompt(query, top3_ids))   # identical prompt structure
    sync(); t_llm = time.perf_counter() - t2

    return {"query": query, "top10": top10, "reranked": ranked, "top3_ids": top3_ids,
            "answer2": answer, "retrieval_ms": t_retr * 1000, "rerank_ms": t_rr * 1000,
            "llm_s": t_llm}

In [19]:
def compare(query, show_text=False):
    """Run both pipelines on one query and print rank shifts, answers and latency."""
    r1 = baseline(query)
    r2 = reranked_pipeline(query)
    assert [i for i, _ in r1["top10"]] == [i for i, _ in r2["top10"]]   # same candidates

    cos = dict(r1["top10"])
    print("QUERY:", query)
    print(f"{'CE rank':<8}{'chunk':<7}{'page':<6}{'bi rank':<9}{'cosine':<9}{'CE score':<10}shift")
    for new_rank, (i, ce, old_rank) in enumerate(r2["reranked"], 1):
        shift = old_rank - new_rank
        arrow = f"#{old_rank} -> #{new_rank}" + (f"  (+{shift})" if shift > 0 else f"  ({shift})" if shift < 0 else "")
        flag = []
        if new_rank <= TOP_N: flag.append("P2")
        if old_rank <= TOP_N: flag.append("P1")
        print(f"#{new_rank:<7}{i:<7}{chunks[i]['page']:<6}#{old_rank:<8}{cos[i]:<9.4f}{ce:<10.3f}{arrow}  {'/'.join(flag)}")

    promoted = [i for i in r2["top3_ids"] if i not in r1["top3_ids"]]
    dropped  = [i for i in r1["top3_ids"] if i not in r2["top3_ids"]]
    print(f"\nPipeline 1 top-3: {r1['top3_ids']}   Pipeline 2 top-3: {r2['top3_ids']}")
    print(f"promoted into top-3: {promoted}   dropped from top-3: {dropped}")
    if show_text:
        for i in promoted:
            print(); show_chunk(i)

    print("\nANSWER 1 (baseline):\n", r1["answer1"])
    print("\nANSWER 2 (re-ranked):\n", r2["answer2"])
    print(f"\nlatency  P1: retrieval {r1['retrieval_ms']:.1f} ms | LLM {r1['llm_s']:.2f} s")
    print(f"         P2: retrieval {r2['retrieval_ms']:.1f} ms + rerank {r2['rerank_ms']:.1f} ms | LLM {r2['llm_s']:.2f} s\n")
    return r1, r2

In [20]:
# smoke test (replace with your failure queries)
r1, r2 = compare("How much revenue did Apple make in China?", show_text=True)

QUERY: How much revenue did Apple make in China?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      197    39    #4       0.6008   5.684     #4 -> #1  (+3)  P2
#2      196    39    #1       0.6269   0.478     #1 -> #2  (-1)  P2/P1
#3      150    25    #2       0.6259   -0.118    #2 -> #3  (-1)  P2/P1
#4      175    32    #3       0.6080   -1.079    #3 -> #4  (-1)  P1
#5      183    36    #7       0.5678   -1.766    #7 -> #5  (+2)
#6      177    33    #5       0.5979   -2.215    #5 -> #6  (-1)
#7      242    50    #6       0.5702   -3.233    #6 -> #7  (-1)
#8      243    50    #9       0.5453   -3.340    #9 -> #8  (+1)
#9      244    51    #8       0.5455   -4.884    #8 -> #9  (-1)
#10     151    26    #10      0.5408   -6.940    #10 -> #10

Pipeline 1 top-3: [196, 150, 175]   Pipeline 2 top-3: [197, 196, 150]
promoted into top-3: [197]   dropped from top-3: [175]

[chunk 197 | page 39]
2025, 2024 and 2023, except in Greater China, where iPhone revenue represented a moderately higher proportion of net sales.

As of September 27, 2025 and September 28, 2024, the Company had total deferred revenue of $13.7 billion and $12.8 billion, respectively. As of September 27, 2025, the Company expects 66% of total deferred revenue to be realized in less than a year, 23% within one-to-two years, 9% within two-to-three years and 2% in greater than three years.

Note 3 – Earnings Per Share

The following table shows the computation of basic and diluted earnings per share for 2025, 2024 and 2023 (net income in millions and shares in thousands):

 2025 2024 2023

 Numerator:

 Net income $ 112,010 $ 93,736 $ 96,995

 Denominator:

 Weighted-average basic shares outstanding 14,948,500 15,343,783 15,744,231

 Effect of dilutive share-based awards 56,197 64,312 68,316

 Weighted-average diluted shares 15,004,697 15,408,095 15,812,547

 Basic earnings per share $ 7.49 $ 6.11 $ 6.16

ANSWER 1 (baseline):
 The context does not contain this information.

ANSWER 2 (re-ranked):
 The context does not contain this information.

latency  P1: retrieval 27.3 ms | LLM 0.28 s
         P2: retrieval 9.7 ms + rerank 18.7 ms | LLM 0.27 s

### 3. Failure Mode Analysis

In [21]:
# Each case: (category, query, gold phrase). The gold chunk is whichever chunk contains
# the gold phrase -> found by text, so it survives re-chunking. Ranks in the comments
# are what we observed (bi-encoder rank -> cross-encoder rank).
FAILURE_QUERIES = [
    # keyword trap: top-1 bi-encoder hit is "The Company designs, manufactures and markets..."
    ("Keyword trap", "Where are Apple's products manufactured?",
     "manufactured by outsourcing partners"),                                    # #4 -> #1
    # exception: general Additional Amounts covenant outranks the "shall not apply" carve-outs
    ("Exception", "Are there exceptions to Apple's obligation to pay Additional Amounts?",
     "shall not apply"),                                                         # #4 -> #1
    # constraint: tax redemption is allowed only "in whole, but not in part"
    ("Negation / constraint", "Can Apple redeem the Notes partially if tax laws change?",
     "in whole, but not in part"),                                               # #4 -> #1
    # negation: Additional Amounts are paid only to holders who are NOT US persons
    ("Negation / constraint", "Does Apple pay additional amounts to US holders?",
     "to a holder who is not a United States person"),                           # #7 -> #2
    # buried: bi-encoder prefers the State Aid history + financial statements, not the $ amount
    ("Buried chunk", "How much did Apple pay in taxes because of the EU State Aid ruling?",
     "one-time income tax charge of $10.2 billion"),                             # #5 -> #2
    ("Buried chunk", "Did Apple change its internal controls in the fourth quarter?",
     "There were no changes in the Company’s internal control"),                 # #8 -> #1
    # distractor: Q4-only monthly repurchase table (89,498K shares) vs full-year figure
    ("Distractor", "How many shares did Apple repurchase in fiscal 2025?",
     "repurchased 402 million shares"),                                          # #8 -> #2
]

# cases where re-ranking does NOT help (for the report's limitations discussion)
LIMITATION_QUERIES = [
    ("Recall failure", "What was the financial impact of the European Court of Justice decision on Apple?",
     "one-time income tax charge of $10.2 billion"),                             # not in top 10
    ("Recall failure", "Which executive is departing Apple?",
     "will transition from his role"),                                           # not in top 10
    ("Re-ranker demotes gold", "Which taxes are excluded from Additional Amounts?",
     "(3) to any Tax that would not have been imposed but for"),                 # #6 -> #7
]

def gold_ids(phrase):
    p = phrase.lower()
    return [c["chunk_id"] for c in chunks if p in re.sub(r"\s+", " ", c["text"]).lower()]

In [22]:
def run_case(category, query, phrase):
    gold = gold_ids(phrase)
    assert gold, f"gold phrase not found: {phrase!r}"
    print("=" * 100); print(f"[{category}]  gold chunk(s): {gold}")
    r1, r2 = compare(query)
    bi = {i: r for r, (i, _) in enumerate(r1["top10"], 1)}
    ce = {i: r for r, (i, _, _) in enumerate(r2["reranked"], 1)}
    g = min(gold, key=lambda i: bi.get(i, 99))            # best-ranked gold chunk
    return {"category": category, "query": query, "gold_chunk": g,
            "bi_rank": bi.get(g, ">10"), "ce_rank": ce.get(g, ">10"),
            "rank_shift": " -> ".join(f"#{x[g]}" if g in x else "not in top 10" for x in (bi, ce)),
            "gold_in_P1_top3": g in r1["top3_ids"], "gold_in_P2_top3": g in r2["top3_ids"],
            "answer1": r1["answer1"], "answer2": r2["answer2"],
            "p1_retrieval_ms": r1["retrieval_ms"], "p2_retrieval_ms": r2["retrieval_ms"],
            "rerank_ms": r2["rerank_ms"], "p1_llm_s": r1["llm_s"], "p2_llm_s": r2["llm_s"]}

results = [run_case(*case) for case in FAILURE_QUERIES]

====================================================================================================
[Keyword trap]  gold chunk(s): [238, 239]
QUERY: Where are Apple's products manufactured?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      239    49    #4       0.5657   3.225     #4 -> #1  (+3)  P2
#2      11     4     #1       0.6133   -0.276    #1 -> #2  (-1)  P2/P1
#3      360    76    #3       0.5678   -1.858    #3 -> #3  P2/P1
#4      57     11    #8       0.5275   -1.982    #8 -> #4  (+4)
#5      12     4     #2       0.6004   -3.094    #2 -> #5  (-3)  P1
#6      15     5     #5       0.5453   -5.006    #5 -> #6  (-1)
#7      175    32    #6       0.5419   -5.093    #6 -> #7  (-1)
#8      145    24    #7       0.5318   -7.892    #7 -> #8  (-1)
#9      186    37    #10      0.5220   -9.290    #10 -> #9  (+1)
#10     196    39    #9       0.5231   -10.110   #9 -> #10  (-1)

Pipeline 1 top-3: [11, 12, 360]   Pipeline 2 top-3: [239, 11, 360]
promoted into top-3: [239]   dropped from top-3: [12]

ANSWER 1 (baseline):
 The context does not contain this information.

ANSWER 2 (re-ranked):
 Apple's products are primarily manufactured by outsourcing partners located in China mainland, India, Japan, South Korea, Taiwan, and Vietnam. The context does not specify the exact locations of all manufacturing sites, only the primary regions.

latency  P1: retrieval 9.5 ms | LLM 0.22 s
         P2: retrieval 8.9 ms + rerank 14.2 ms | LLM 0.89 s

====================================================================================================
[Exception]  gold chunk(s): [310]
QUERY: Are there exceptions to Apple's obligation to pay Additional Amounts?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      310    66    #4       0.5711   1.459     #4 -> #1  (+3)  P2
#2      309    66    #1       0.6112   -0.087    #1 -> #2  (-1)  P2/P1
#3      318    67    #6       0.5682   -0.822    #6 -> #3  (+3)  P2
#4      316    67    #2       0.6088   -2.362    #2 -> #4  (-2)  P1
#5      193    38    #8       0.5652   -4.688    #8 -> #5  (+3)
#6      102    17    #3       0.5780   -4.915    #3 -> #6  (-3)  P1
#7      279    59    #7       0.5670   -6.992    #7 -> #7
#8      192    38    #5       0.5682   -7.293    #5 -> #8  (-3)
#9      296    64    #9       0.5555   -7.696    #9 -> #9
#10     135    21    #10      0.5545   -9.683    #10 -> #10

Pipeline 1 top-3: [309, 316, 102]   Pipeline 2 top-3: [310, 309, 318]
promoted into top-3: [310, 318]   dropped from top-3: [316, 102]

ANSWER 1 (baseline):
 Yes, there are exceptions to Apple's obligation to pay Additional Amounts. The context indicates that the obligation to pay Additional Amounts is subject to "exceptions and limitations set forth below," although the specific exceptions and limitations are not detailed in the provided context.

ANSWER 2 (re-ranked):
 Yes, there are exceptions to Apple's obligation to pay Additional Amounts. The obligation does not apply to any Tax imposed by reason of the holder (or the beneficial owner for whose benefit such holder holds the Notes), or a fiduciary, settlor, beneficiary, member or shareholder of the holder if the holder is an estate, trust, partnership or corporation, or a person holding a power over an estate or trust administered by a fiduciary holder, being considered as:

(a) being or having been engaged in a trade or business in the United States or having or having had a permanent establishment in the United States;

(b) having a current or former connection with the United States (other than a connection arising solely as a result of the ownership of the Notes, the receipt of any payment or the enforcement of any rights.

latency  P1: retrieval 9.5 ms | LLM 1.02 s
         P2: retrieval 9.3 ms + rerank 13.6 ms | LLM 3.20 s

====================================================================================================
[Negation / constraint]  gold chunk(s): [318]
QUERY: Can Apple redeem the Notes partially if tax laws change?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      318    67    #4       0.6101   -3.204    #4 -> #1  (+3)  P2
#2      342    72    #5       0.6011   -3.904    #5 -> #2  (+3)  P2
#3      320    68    #3       0.6231   -5.081    #3 -> #3  P2/P1
#4      321    68    #8       0.5820   -5.808    #8 -> #4  (+4)
#5      279    59    #1       0.6421   -6.300    #1 -> #5  (-4)  P1
#6      313    67    #10      0.5757   -6.406    #10 -> #6  (+4)
#7      309    66    #6       0.5846   -6.594    #6 -> #7  (-1)
#8      287    62    #2       0.6324   -6.863    #2 -> #8  (-6)  P1
#9      310    66    #9       0.5814   -7.928    #9 -> #9
#10     308    66    #7       0.5832   -8.132    #7 -> #10  (-3)

Pipeline 1 top-3: [279, 287, 320]   Pipeline 2 top-3: [318, 342, 320]
promoted into top-3: [318, 342]   dropped from top-3: [279, 287]

ANSWER 1 (baseline):
 The context does not contain this information.

ANSWER 2 (re-ranked):
 The context indicates that Apple (or the issuer) may redeem the Notes partially if tax laws change, but only for specific series of Notes. Specifically, the 2026 Notes, the 2027 Notes, the 3.050% 2029 Notes, and the 2042 Notes can be redeemed in whole or in part at the issuer's option. However, the 1.375% 2029 Notes and the 2025 Notes and 2031 Notes have different notice periods for redemption. The redemption price for these Notes is determined based on specific conditions, including the greater of 100% of the principal amount or the present value of remaining payments discounted at the Comparable Government Bond Rate plus applicable basis points. The context does not specify whether partial redemption is allowed for all series of Notes in the event of a tax law change, but it does allow for partial redemption for the 2026, 2027, 3.050% 2029, and 2042 Notes.

latency  P1: retrieval 8.8 ms | LLM 0.26 s
         P2: retrieval 7.5 ms + rerank 13.9 ms | LLM 4.43 s

====================================================================================================
[Negation / constraint]  gold chunk(s): [309]
QUERY: Does Apple pay additional amounts to US holders?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      181    35    #3       0.5924   1.780     #3 -> #1  (+2)  P2/P1
#2      309    66    #7       0.5734   -0.837    #7 -> #2  (+5)  P2
#3      175    32    #9       0.5692   -5.437    #9 -> #3  (+6)  P2
#4      177    33    #4       0.5909   -6.367    #4 -> #4
#5      287    62    #6       0.5828   -6.596    #6 -> #5  (+1)
#6      279    59    #2       0.6020   -7.954    #2 -> #6  (-4)  P1
#7      15     5     #1       0.6065   -8.277    #1 -> #7  (-6)  P1
#8      193    38    #5       0.5831   -9.587    #5 -> #8  (-3)
#9      11     4     #10      0.5692   -10.242   #10 -> #9  (+1)
#10     192    38    #8       0.5692   -11.013   #8 -> #10  (-2)

Pipeline 1 top-3: [15, 279, 181]   Pipeline 2 top-3: [181, 309, 175]
promoted into top-3: [309, 175]   dropped from top-3: [15, 279]

ANSWER 1 (baseline):
 The context does not contain this information.

ANSWER 2 (re-ranked):
 The context does not contain this information.

latency  P1: retrieval 9.3 ms | LLM 0.26 s
         P2: retrieval 7.9 ms + rerank 14.2 ms | LLM 0.27 s

====================================================================================================
[Buried chunk]  gold chunk(s): [215]
QUERY: How much did Apple pay in taxes because of the EU State Aid ruling?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      213    43    #4       0.5575   -0.107    #4 -> #1  (+3)  P2
#2      215    43    #5       0.5504   -0.940    #5 -> #2  (+3)  P2
#3      214    43    #1       0.6293   -2.405    #1 -> #3  (-2)  P2/P1
#4      177    33    #2       0.5665   -3.089    #2 -> #4  (-2)  P1
#5      181    35    #8       0.5245   -4.608    #8 -> #5  (+3)
#6      175    32    #3       0.5603   -4.751    #3 -> #6  (-3)  P1
#7      183    36    #6       0.5350   -5.183    #6 -> #7  (-1)
#8      179    34    #9       0.5204   -5.955    #9 -> #8  (+1)
#9      196    39    #7       0.5268   -8.255    #7 -> #9  (-2)
#10     132    21    #10      0.5068   -9.954    #10 -> #10

Pipeline 1 top-3: [214, 177, 175]   Pipeline 2 top-3: [213, 215, 214]
promoted into top-3: [213, 215]   dropped from top-3: [177, 175]

ANSWER 1 (baseline):
 The context does not contain this information.

ANSWER 2 (re-ranked):
 Apple recorded a one-time income tax charge of $10.2 billion, net, due to the EU State Aid ruling. This charge represented $15.8 billion payable to Ireland via the release of amounts held in escrow, partially offset by a U.S. foreign tax credit of $4.8 billion and a decrease in unrecognized tax benefits of $823 million.

latency  P1: retrieval 8.7 ms | LLM 0.27 s
         P2: retrieval 8.5 ms + rerank 14.9 ms | LLM 1.57 s

====================================================================================================
[Buried chunk]  gold chunk(s): [263]
QUERY: Did Apple change its internal controls in the fourth quarter?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      263    55    #8       0.5377   2.005     #8 -> #1  (+7)  P2
#2      366    78    #10      0.5310   -0.744    #10 -> #2  (+8)  P2
#3      253    54    #1       0.6144   -0.795    #1 -> #3  (-2)  P2/P1
#4      145    24    #4       0.5570   -3.712    #4 -> #4
#5      186    37    #3       0.5577   -7.507    #3 -> #5  (-2)  P1
#6      11     4     #5       0.5560   -8.976    #5 -> #6  (-1)
#7      245    52    #6       0.5428   -9.635    #6 -> #7  (-1)
#8      146    24    #7       0.5377   -10.677   #7 -> #8  (-1)
#9      279    59    #2       0.5691   -10.779   #2 -> #9  (-7)  P1
#10     135    21    #9       0.5325   -10.997   #9 -> #10  (-1)

Pipeline 1 top-3: [253, 279, 186]   Pipeline 2 top-3: [263, 366, 253]
promoted into top-3: [263, 366]   dropped from top-3: [279, 186]

ANSWER 1 (baseline):
 The context does not contain this information.

ANSWER 2 (re-ranked):
 Answer: No, Apple did not change its internal controls over financial reporting in the fourth quarter of 2025. The context explicitly states that there were no changes in the Company’s internal control over financial reporting during the fourth quarter of 2025 that materially affected, or are reasonably likely to materially affect, the Company’s internal control over financial reporting.

latency  P1: retrieval 8.6 ms | LLM 0.25 s
         P2: retrieval 8.0 ms + rerank 12.7 ms | LLM 1.45 s

====================================================================================================
[Distractor]  gold chunk(s): [230]
QUERY: How many shares did Apple repurchase in fiscal 2025?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      231    48    #2       0.6422   6.492     #2 -> #1  (+1)  P2/P1
#2      230    47    #8       0.5901   4.812     #8 -> #2  (+6)  P2
#3      181    35    #5       0.6078   4.511     #5 -> #3  (+2)  P2
#4      197    39    #7       0.5908   2.647     #7 -> #4  (+3)
#5      175    32    #6       0.5918   2.379     #6 -> #5  (+1)
#6      140    22    #1       0.6438   1.611     #1 -> #6  (-5)  P1
#7      183    36    #10      0.5833   1.006     #10 -> #7  (+3)
#8      287    62    #4       0.6188   -0.624    #4 -> #8  (-4)
#9      196    39    #3       0.6204   -2.866    #3 -> #9  (-6)  P1
#10     150    25    #9       0.5886   -4.559    #9 -> #10  (-1)

Pipeline 1 top-3: [140, 231, 196]   Pipeline 2 top-3: [231, 230, 181]
promoted into top-3: [230, 181]   dropped from top-3: [140, 196]

ANSWER 1 (baseline):
 Apple repurchased 401,672 thousand shares in fiscal 2025.

ANSWER 2 (re-ranked):
 Apple repurchased 402 million shares in fiscal 2025.

latency  P1: retrieval 8.1 ms | LLM 0.50 s
         P2: retrieval 8.0 ms + rerank 13.4 ms | LLM 0.43 s

In [23]:
import pandas as pd
pd.set_option("display.max_colwidth", 80)

df = pd.DataFrame(results)
df[["category", "query", "gold_chunk", "rank_shift", "gold_in_P1_top3", "gold_in_P2_top3"]]

,category,query,gold_chunk,rank_shift,gold_in_P1_top3,gold_in_P2_top3
0,Keyword trap,Where are Apple's products manufactured?,239,#4 -> #1,False,True
1,Exception,Are there exceptions to Apple's obligation to pay Additional Amounts?,310,#4 -> #1,False,True
2,Negation / constraint,Can Apple redeem the Notes partially if tax laws change?,318,#4 -> #1,False,True
3,Negation / constraint,Does Apple pay additional amounts to US holders?,309,#7 -> #2,False,True
4,Buried chunk,How much did Apple pay in taxes because of the EU State Aid ruling?,215,#5 -> #2,False,True
5,Buried chunk,Did Apple change its internal controls in the fourth quarter?,263,#8 -> #1,False,True
6,Distractor,How many shares did Apple repurchase in fiscal 2025?,230,#8 -> #2,False,True

In [24]:
# side-by-side answers for the report (Answer 1 vs Answer 2)
for r in results:
    print("=" * 100)
    print(f"[{r['category']}] {r['query']}   (gold chunk {r['gold_chunk']}: #{r['bi_rank']} -> #{r['ce_rank']})")
    print("\nANSWER 1:", r["answer1"])
    print("\nANSWER 2:", r["answer2"], "\n")

====================================================================================================
[Keyword trap] Where are Apple's products manufactured?   (gold chunk 239: #4 -> #1)

ANSWER 1: The context does not contain this information.

ANSWER 2: Apple's products are primarily manufactured by outsourcing partners located in China mainland, India, Japan, South Korea, Taiwan, and Vietnam. The context does not specify the exact locations of all manufacturing sites, only the primary regions.

====================================================================================================
[Exception] Are there exceptions to Apple's obligation to pay Additional Amounts?   (gold chunk 310: #4 -> #1)

ANSWER 1: Yes, there are exceptions to Apple's obligation to pay Additional Amounts. The context indicates that the obligation to pay Additional Amounts is subject to "exceptions and limitations set forth below," although the specific exceptions and limitations are not detailed in the provided context.

ANSWER 2: Yes, there are exceptions to Apple's obligation to pay Additional Amounts. The obligation does not apply to any Tax imposed by reason of the holder (or the beneficial owner for whose benefit such holder holds the Notes), or a fiduciary, settlor, beneficiary, member or shareholder of the holder if the holder is an estate, trust, partnership or corporation, or a person holding a power over an estate or trust administered by a fiduciary holder, being considered as:

(a) being or having been engaged in a trade or business in the United States or having or having had a permanent establishment in the United States;

(b) having a current or former connection with the United States (other than a connection arising solely as a result of the ownership of the Notes, the receipt of any payment or the enforcement of any rights.

====================================================================================================
[Negation / constraint] Can Apple redeem the Notes partially if tax laws change?   (gold chunk 318: #4 -> #1)

ANSWER 1: The context does not contain this information.

ANSWER 2: The context indicates that Apple (or the issuer) may redeem the Notes partially if tax laws change, but only for specific series of Notes. Specifically, the 2026 Notes, the 2027 Notes, the 3.050% 2029 Notes, and the 2042 Notes can be redeemed in whole or in part at the issuer's option. However, the 1.375% 2029 Notes and the 2025 Notes and 2031 Notes have different notice periods for redemption. The redemption price for these Notes is determined based on specific conditions, including the greater of 100% of the principal amount or the present value of remaining payments discounted at the Comparable Government Bond Rate plus applicable basis points. The context does not specify whether partial redemption is allowed for all series of Notes in the event of a tax law change, but it does allow for partial redemption for the 2026, 2027, 3.050% 2029, and 2042 Notes.

====================================================================================================
[Negation / constraint] Does Apple pay additional amounts to US holders?   (gold chunk 309: #7 -> #2)

ANSWER 1: The context does not contain this information.

ANSWER 2: The context does not contain this information.

====================================================================================================
[Buried chunk] How much did Apple pay in taxes because of the EU State Aid ruling?   (gold chunk 215: #5 -> #2)

ANSWER 1: The context does not contain this information.

ANSWER 2: Apple recorded a one-time income tax charge of $10.2 billion, net, due to the EU State Aid ruling. This charge represented $15.8 billion payable to Ireland via the release of amounts held in escrow, partially offset by a U.S. foreign tax credit of $4.8 billion and a decrease in unrecognized tax benefits of $823 million.

====================================================================================================
[Buried chunk] Did Apple change its internal controls in the fourth quarter?   (gold chunk 263: #8 -> #1)

ANSWER 1: The context does not contain this information.

ANSWER 2: Answer: No, Apple did not change its internal controls over financial reporting in the fourth quarter of 2025. The context explicitly states that there were no changes in the Company’s internal control over financial reporting during the fourth quarter of 2025 that materially affected, or are reasonably likely to materially affect, the Company’s internal control over financial reporting.

====================================================================================================
[Distractor] How many shares did Apple repurchase in fiscal 2025?   (gold chunk 230: #8 -> #2)

ANSWER 1: Apple repurchased 401,672 thousand shares in fiscal 2025.

ANSWER 2: Apple repurchased 402 million shares in fiscal 2025.

#### Where re-ranking does not help

In [25]:
# a cross-encoder can only re-order what the bi-encoder retrieved: if the gold chunk is
# not in the top 10, no amount of re-ranking will recover it
lim = pd.DataFrame([run_case(*case) for case in LIMITATION_QUERIES])
lim[["category", "query", "gold_chunk", "rank_shift", "gold_in_P1_top3", "gold_in_P2_top3"]]

====================================================================================================
[Recall failure]  gold chunk(s): [215]
QUERY: What was the financial impact of the European Court of Justice decision on Apple?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      214    43    #2       0.5593   -4.161    #2 -> #1  (+1)  P2/P1
#2      103    17    #10      0.5097   -6.718    #10 -> #2  (+8)  P2
#3      150    25    #4       0.5451   -7.537    #4 -> #3  (+1)  P2
#4      181    35    #8       0.5181   -8.944    #8 -> #4  (+4)
#5      175    32    #7       0.5202   -9.152    #7 -> #5  (+2)
#6      102    17    #6       0.5400   -9.171    #6 -> #6
#7      177    33    #3       0.5502   -9.310    #3 -> #7  (-4)  P1
#8      104    17    #1       0.5655   -9.792    #1 -> #8  (-7)  P1
#9      132    21    #5       0.5429   -10.510   #5 -> #9  (-4)
#10     279    59    #9       0.5131   -10.583   #9 -> #10  (-1)

Pipeline 1 top-3: [104, 214, 177]   Pipeline 2 top-3: [214, 103, 150]
promoted into top-3: [103, 150]   dropped from top-3: [104, 177]

ANSWER 1 (baseline):
 The European Court of Justice (ECJ) decision confirmed the Commission’s 2016 State Aid Decision, which ordered Ireland to calculate and recover additional taxes from Apple for the period June 2003 through December 2014. This decision could result in Apple owing additional taxes to Ireland, which would have a financial impact on the company. However, the context does not specify the exact financial impact or amount.

ANSWER 2 (re-ranked):
 The context does not contain this information.

latency  P1: retrieval 10.8 ms | LLM 1.72 s
         P2: retrieval 8.6 ms + rerank 13.4 ms | LLM 0.24 s

====================================================================================================
[Recall failure]  gold chunk(s): [264]
QUERY: Which executive is departing Apple?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      375    80    #3       0.5277   -3.754    #3 -> #1  (+2)  P2/P1
#2      374    80    #4       0.5273   -4.132    #4 -> #2  (+2)  P2
#3      279    59    #2       0.5314   -8.202    #2 -> #3  (-1)  P2/P1
#4      284    61    #1       0.5513   -8.777    #1 -> #4  (-3)  P1
#5      280    59    #8       0.5010   -9.258    #8 -> #5  (+3)
#6      253    54    #10      0.4915   -9.737    #10 -> #6  (+4)
#7      11     4     #6       0.5155   -10.048   #6 -> #7  (-1)
#8      285    61    #9       0.4941   -11.008   #9 -> #8  (+1)
#9      12     4     #5       0.5212   -11.049   #5 -> #9  (-4)
#10     145    24    #7       0.5080   -11.109   #7 -> #10  (-3)

Pipeline 1 top-3: [284, 279, 375]   Pipeline 2 top-3: [375, 374, 279]
promoted into top-3: [374]   dropped from top-3: [284]

ANSWER 1 (baseline):
 The context does not contain this information.

ANSWER 2 (re-ranked):
 The context does not contain this information.

latency  P1: retrieval 8.2 ms | LLM 0.25 s
         P2: retrieval 7.9 ms + rerank 13.7 ms | LLM 0.26 s

====================================================================================================
[Re-ranker demotes gold]  gold chunk(s): [313]
QUERY: Which taxes are excluded from Additional Amounts?
CE rank chunk  page  bi rank  cosine   CE score  shift
#1      309    66    #2       0.5757   1.222     #2 -> #1  (+1)  P2/P1
#2      310    66    #3       0.5400   0.747     #3 -> #2  (+1)  P2/P1
#3      316    67    #1       0.6338   0.741     #1 -> #3  (-2)  P2/P1
#4      308    66    #4       0.5038   -2.412    #4 -> #4
#5      318    67    #8       0.4745   -3.043    #8 -> #5  (+3)
#6      303    65    #9       0.4680   -5.766    #9 -> #6  (+3)
#7      313    67    #6       0.4854   -6.866    #6 -> #7  (-1)
#8      314    67    #5       0.4984   -7.580    #5 -> #8  (-3)
#9      315    67    #10      0.4592   -8.535    #10 -> #9  (+1)
#10     249    52    #7       0.4778   -8.722    #7 -> #10  (-3)

Pipeline 1 top-3: [316, 309, 310]   Pipeline 2 top-3: [309, 310, 316]
promoted into top-3: []   dropped from top-3: []

ANSWER 1 (baseline):
 The taxes excluded from Additional Amounts are those imposed by reason of the holder (or the beneficial owner for whose benefit such holder holds the Notes), or a fiduciary, settlor, beneficiary, member or shareholder of the holder if the holder is an estate, trust, partnership or corporation, or a person holding a power over an estate or trust administered by a fiduciary holder, being considered as:

(a) being or having been engaged in a trade or business in the United States or having or having had a permanent establishment in the United States;

(b) having a current or former connection with the United States (other than a connection arising solely as a result of the ownership of the Notes, the receipt of any payment or the enforcement of any rights.

ANSWER 2 (re-ranked):
 The taxes excluded from Additional Amounts are those imposed by reason of the holder (or the beneficial owner for whose benefit such holder holds the Notes), or a fiduciary, settlor, beneficiary, member or shareholder of the holder if the holder is an estate, trust, partnership or corporation, or a person holding a power over an estate or trust administered by a fiduciary holder, being considered as:

(a) being or having been engaged in a trade or business in the United States or having or having had a permanent establishment in the United States;

(b) having a current or former connection with the United States (other than a connection arising solely as a result of the ownership of the Notes, the receipt of any payment or the enforcement of any rights.

latency  P1: retrieval 9.4 ms | LLM 2.92 s
         P2: retrieval 9.9 ms + rerank 12.2 ms | LLM 2.91 s

,category,query,gold_chunk,rank_shift,gold_in_P1_top3,gold_in_P2_top3
0,Recall failure,What was the financial impact of the European Court of Justice decision on A...,215,not in top 10 -> not in top 10,False,False
1,Recall failure,Which executive is departing Apple?,264,not in top 10 -> not in top 10,False,False
2,Re-ranker demotes gold,Which taxes are excluded from Additional Amounts?,313,#6 -> #7,False,False

### 4. Latency Profiling

In [26]:
all_runs = pd.concat([df, lim], ignore_index=True)
lat = pd.DataFrame({
    "Pipeline 1 (baseline)": {
        "retrieval (ms)": all_runs.p1_retrieval_ms.mean(),
        "re-rank (ms)": 0.0,
        "retrieval total (ms)": all_runs.p1_retrieval_ms.mean(),
        "LLM generation (s)": all_runs.p1_llm_s.mean()},
    "Pipeline 2 (re-rank)": {
        "retrieval (ms)": all_runs.p2_retrieval_ms.mean(),
        "re-rank (ms)": all_runs.rerank_ms.mean(),
        "retrieval total (ms)": (all_runs.p2_retrieval_ms + all_runs.rerank_ms).mean(),
        "LLM generation (s)": all_runs.p2_llm_s.mean()},
}).round(2)
print(f"mean over {len(all_runs)} queries")
lat

mean over 10 queries

                      Pipeline 1 (baseline)  Pipeline 2 (re-rank)
retrieval (ms)                         9.08                  8.46
re-rank (ms)                           0.00                 13.62
retrieval total (ms)                   9.08                 22.07
LLM generation (s)                     0.77                  1.57